INSERT INTO domains (name) 
VALUES
    ('Algorithms & Data Structures'),
    ('Operating Systems'),
    ('Computer Networks'),
    ('Database Systems'),
    ('Computer Architecture'),
    ('Compilers'),
    ('Theory of Computation'),
    ('Web Development (Frontend)'),
    ('Web Development (Backend)'),
    ('Mobile App Development'),
    ('Desktop App Development'),
    ('Full Stack Development'),
    ('Game Development'),
    ('Software Engineering & SDLC'),
    ('Machine Learning'),
    ('Deep Learning'),
    ('Natural Language Processing (NLP)'),
    ('Computer Vision'),
    ('Data Science'),
    ('Data Analytics'),
    ('Reinforcement Learning'),
    ('Cybersecurity'),
    ('Cryptography'),
    ('Network Security'),
    ('Ethical Hacking'),
    ('Cloud Computing (AWS, Azure, GCP)'),
    ('DevOps & CI/CD'),
    ('Containerization (Docker, Kubernetes)'),
    ('Discrete Mathematics'),
    ('Graph Theory'),
    ('Linear Algebra for CS'),
    ('Probability & Statistics for CS'),
    ('Embedded Systems'),
    ('Internet of Things (IoT)'),
    ('Distributed Systems'),
    ('Parallel Computing'),
    ('Edge & Fog Computing'),
    ('Quantum Computing'),
    ('Augmented/Virtual Reality (AR/VR)'),
    ('Blockchain & Web3'),
    ('Robotics'),
    ('Digital Signal Processing')
;

INSERT INTO languages (name) 
VALUES
    ('English'),
    ('Hindi'),
    ('Spanish'),
    ('French'),
    ('German'),
    ('Chinese'),
    ('Japanese'),
    ('Korean'),
    ('Arabic'),
    ('Portuguese'),
    ('Russian'),
    ('Malayalam'),
    ('Tamil'),
    ('Telugu'),
    ('Bengali'),
    ('Gujarati'),
    ('Punjabi'),
    ('Marathi'),
    ('Urdu')
;

INSERT INTO coding_languages (name) 
VALUES
    ('C'),
    ('C++'),
    ('Java'),
    ('Python'),
    ('JavaScript'),
    ('TypeScript'),
    ('Go'),
    ('Rust'),
    ('C#'),
    ('Kotlin'),
    ('Swift'),
    ('PHP'),
    ('Ruby'),
    ('R'),
    ('SQL'),
    ('NoSQL'),
    ('HTML'),
    ('CSS'),
    ('Bash/Shell'),
    ('MATLAB'),
    ('Dart'),
    ('Scala'),
    ('Perl'),
    ('Assembly'),
    ('Haskell'),
    ('Elixir')
;
